version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 tuniforme.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tuniforme
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password